
package recipestorage.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecipeDBService", targetNamespace = "http://service.recipestorage/", wsdlLocation = "https://isdemm-recipe-storage-service.herokuapp.com/recipeDB?wsdl")
public class RecipeDBService
    extends Service
{

    private final static URL RECIPEDBSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECIPEDBSERVICE_EXCEPTION;
    private final static QName RECIPEDBSERVICE_QNAME = new QName("http://service.recipestorage/", "RecipeDBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://isdemm-recipe-storage-service.herokuapp.com/recipeDB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECIPEDBSERVICE_WSDL_LOCATION = url;
        RECIPEDBSERVICE_EXCEPTION = e;
    }

    public RecipeDBService() {
        super(__getWsdlLocation(), RECIPEDBSERVICE_QNAME);
    }

    public RecipeDBService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECIPEDBSERVICE_QNAME, features);
    }

    public RecipeDBService(URL wsdlLocation) {
        super(wsdlLocation, RECIPEDBSERVICE_QNAME);
    }

    public RecipeDBService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECIPEDBSERVICE_QNAME, features);
    }

    public RecipeDBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecipeDBService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecipeDBInterface
     */
    @WebEndpoint(name = "RecipeDBPort")
    public RecipeDBInterface getRecipeDBPort() {
        return super.getPort(new QName("http://service.recipestorage/", "RecipeDBPort"), RecipeDBInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecipeDBInterface
     */
    @WebEndpoint(name = "RecipeDBPort")
    public RecipeDBInterface getRecipeDBPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.recipestorage/", "RecipeDBPort"), RecipeDBInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECIPEDBSERVICE_EXCEPTION!= null) {
            throw RECIPEDBSERVICE_EXCEPTION;
        }
        return RECIPEDBSERVICE_WSDL_LOCATION;
    }

}
